name: Backend CI

on:
  push:
    paths:
      - 'carcrud/**'
  pull_request:
    paths:
      - 'carcrud/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build + SonarCloud
        working-directory: ./carcrud
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=23suca12devops \
          -Dsonar.organization=23suca12devops-org \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}